### ISSUE TITLE
Design/Layout Test Automation

### ISSUE THREAD

**Issue by rivenirvana** [starkfire/Caviar#4]
I'm currently thinking of a way to "automate" the testing of the source's visual design and layout. Maybe something that reads the compiled source and outputs an HTML file with test elements utilizing selectors within the stylesheet instead of manually creating the test files.

What do you think about the feasibility and practicality of this, including if you know of possible routes it can be approached using other tools, and if it should even coexist with the source in this repository.

**Comment by starkfire** [comment]
Will publish a documentation of the UI elements once a Grid System has been implemented. Testing can be done with either Gulp or Grunt, but I used Gulp instead (you can add 'watch' and 'browsersync' tasks for convenience, but having a little bit of trouble with it on Gulp 4).

**Comment by starkfire** [comment]
Will publish a documentation of the UI elements once a Grid System has been implemented. As of now, only Gulp can be used for testing (but you can also use Grunt). You can add 'watch' and 'browsersync' tasks for convenience, but having a little bit of trouble with it on Gulp 4.

Haven't given that much thought on test tools yet, but for visual regression tests: BackstopJS, PhantomCSS and CasperJS can be used.
